添加用户搜索，插画搜索包括翻译参数
mixmoe/HibiAPI pull request #383
Opened 2023-01-31 17:17 UTC by yeyang52

2023-01-31 17:28 UTC, mnixry requested changes
整体看起来没什么问题，对照 https://github.com/mixmoe/HibiAPI/blob/main/test/test_pixiv.py 前面的代码为新添加的API写一个测试就能合并了应该

2023-01-31 17:28 UTC, mnixry commented on hibiapi/api/pixiv/api.py
> +        include_translated_tag_results: bool = True,
这个参数名有点太长了，你可以把它改成短一些的名字吗，~~感觉看着很丑~~

2023-01-31 17:36 UTC, yeyang52 commented on hibiapi/api/pixiv/api.py
> +        include_translated_tag_results: bool = True,
search_novel也有这个参数

2023-01-31 17:38 UTC, yeyang52 commented on hibiapi/api/pixiv/api.py
> +        include_translated_tag_results: bool = True,
> 

我已经添加好了

2023-01-31 17:42 UTC, mnixry approved these changes
嗯，测试能过的话看着就没什么问题了

P.S. 你要不要把标签补全那个API也顺手加上？不加的话我明天来加

2023-01-31 17:42 UTC, mnixry commented on test/test_pixiv.py
> +    response = client.get("search_user", params={"word": "鬼针草"})
~~非常有品位的选择~~

2023-01-31 17:44 UTC, yeyang52 commented on test/test_pixiv.py
> +    response = client.get("search_user", params={"word": "鬼针草"})
我发现还有offset的参数等我添加一下

2023-01-31 17:55 UTC, yeyang52 commented on test/test_pixiv.py
> +    response = client.get("search_user", params={"word": "鬼针草"})
我已经添加好了

2023-01-31 18:14 UTC, mnixry commented on test/test_pixiv.py
> +    response = client.get("tags_autocomplete")
```
client = <starlette.testclient.TestClient object at 0x7f785af65460>

    def test_tags_autocomplete(client: TestClient):
        response = client.get("tags_autocomplete")
>       assert response.status_code == 200
E       assert 422 == 200
E        +  where 422 = <Response [422 Unprocessable Entity]>.status_code
```

测试寄了，你好像没加`word`参数，参考上面的写一下

2023-01-31 18:19 UTC, yeyang52 commented on test/test_pixiv.py
> +    response = client.get("tags_autocomplete")
草，直接复制的上面的没看见

2023-01-31 18:23 UTC, mnixry approved these changes
没问题了，感谢PR，早点休息

2023-02-01 01:27 UTC, merged

2023-02-01 01:30 UTC, mnixry commented
@all-contributors please add @yeyang52 for code