feat: 添加几条 Pixiv API
mixmoe/HibiAPI pull request #385
Opened 2023-02-02 07:36 UTC by asadahimeka

新增了如下几条 API

- 用户收藏的小说
- 热门插画作品预览
- 大家的新作品（插画）
- pixivision(亮点/特辑) 列表
- 插画评论列表
- 插画评论回复
- 小说评论列表
- 小说评论回复
- 小说排行榜
- 热门小说标签
- 热门小说作品预览

都没有设置 `@cache_config`

2023-02-02 10:12 UTC, mnixry requested changes
感谢PR，这里有几个细节需要稍微修改一下，其他地方没什么问题

~~不知道测试为什么莫名其妙Rate Limit了，应该没这么脆弱才对啊~~

2023-02-02 10:12 UTC, mnixry commented on hibiapi/api/pixiv/api.py
> +            },
这些硬编码的参数你试试能不能参考这个，改成用户可以定义的，下面的热门小说预览也试一试

https://github.com/mixmoe/HibiAPI/blob/6affc35583445c8d589416fb3040d913843e6301/hibiapi/api/pixiv/api.py#L328-L352

2023-02-02 10:12 UTC, mnixry commented on hibiapi/api/pixiv/api.py
> +    async def tags_novel(self):
这个小说热门标签的缓存时间可以参考之前的适度拉长
https://github.com/mixmoe/HibiAPI/blob/6affc35583445c8d589416fb3040d913843e6301/hibiapi/api/pixiv/api.py#L287-L289

2023-02-02 11:51 UTC, asadahimeka commented on hibiapi/api/pixiv/api.py
> +        include_total_comments: Optional[bool] = None,
这个好像是 v1 的参数 我忘删了

2023-02-02 11:54 UTC, asadahimeka commented
修改了（我也不懂 py，照葫芦画瓢，有什么错误请见谅 😌

2023-02-02 14:36 UTC, mnixry approved these changes
看着没问题了，lint这个问题你想修就修，我这两天在火车上没时间合

2023-02-03 02:08 UTC, asadahimeka commented
OK 多了个空格 修了

2023-02-04 13:57 UTC, merged